// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CallToAction: typeof import('./components/CallToAction.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Footerb: typeof import('./components/Footerb.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    Testimonals: typeof import('./components/Testimonals.vue')['default']
  }
}

export { }
